name: Autograding Tests

on:
  push:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test_1
        id: test_1
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: test_1
          setup-command: pip install pytest pylint
          command: pytest tests/test_1.py
          timeout: 10
          max-score: 10

